"""view newest tasks default=True

Revision ID: 499704b2aea8
Revises: f5247bd2ceba
Create Date: 2019-08-15 19:18:52.210072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499704b2aea8'
down_revision = 'f5247bd2ceba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'list_as_descending')
    op.drop_column('user', 'list_by_due_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('list_by_due_date', sa.BOOLEAN(), nullable=True))
    op.add_column('user', sa.Column('list_as_descending', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
