"""Add due date variables and functions

Revision ID: 774ea042a94a
Revises: 6e22d7b7610a
Create Date: 2019-08-14 18:23:04.519045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774ea042a94a'
down_revision = '6e22d7b7610a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('due_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_task_due_date'), 'task', ['due_date'], unique=False)
    op.add_column('user', sa.Column('list_by_due_date', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'list_by_due_date')
    op.drop_index(op.f('ix_task_due_date'), table_name='task')
    op.drop_column('task', 'due_date')
    # ### end Alembic commands ###
