"""rename task sort columns

Revision ID: f5247bd2ceba
Revises: 774ea042a94a
Create Date: 2019-08-15 19:12:02.700250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5247bd2ceba'
down_revision = '774ea042a94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('view_tasks_by_due_date', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('view_tasks_by_newest', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'view_tasks_by_newest')
    op.drop_column('user', 'view_tasks_by_due_date')
    # ### end Alembic commands ###
